version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    target-branch: "night-builds"
    # Labels on pull requests for version updates only
    labels:
      - "npm dependencies"
